# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env: # lookup key as an environment variable
        YODLEE_CLIENT_ID: ${{ secrets.YODLEE_CLIENT_ID }}
        YODLEE_SECRET: ${{secrets.YODLEE_SECRET}}
        YODLEE_ADMIN: ${{secrets.YODLEE_ADMIN}}
      run: mvn -B package --file pom.xml
